-- creating background for the bars --
local function CreateBorderTextures(bar)
	bar.actionButtons[1].abfBorderArt = bar.actionButtons[1]:CreateTexture(nil, "BACKGROUND", nil, -3)
	bar.actionButtons[1].abfBorderArt:SetAtlas("UI-HUD-ActionBar-Frame", false, "LINEAR")
	bar.actionButtons[1].abfBorderArt:ClearAllPoints()
	bar.actionButtons[1].abfBorderArt:SetPoint("TOPLEFT", bar, "TOPLEFT", -4, 4)
	bar.actionButtons[1].abfBorderArt:SetPoint("BOTTOMRIGHT", bar, "BOTTOMRIGHT", 8, -7)
	bar.actionButtons[1].abfBorderArt:Hide()
end
CreateBorderTextures(MultiBarBottomLeft)
CreateBorderTextures(MultiBarBottomRight)
CreateBorderTextures(MultiBarRight)
CreateBorderTextures(MultiBarLeft)
CreateBorderTextures(MultiBar5)
CreateBorderTextures(MultiBar6)
CreateBorderTextures(MultiBar7)