-- creating background for the bars --
local function backgroundBarTexture(self)
	self:SetAtlas("UI-HUD-ActionBar-Frame", false, "LINEAR")
	self:Hide()
end
-- bar 1 --
-- in Zlave--
-- bar 2 --
local texture = MultiBarBottomLeft:CreateTexture("$parentABFbackground", "BACKGROUND", nil, -8)
texture:SetPoint("TOPLEFT", MultiBarBottomLeft, "TOPLEFT", -4, -4)
texture:SetPoint("BOTTOMRIGHT", MultiBarBottomLeft, "BOTTOMRIGHT", 4, -8)
backgroundBarTexture(texture)
-- bar 3 --
local texture = MultiBarBottomRight:CreateTexture("$parentABFbackground", "BACKGROUND", nil, -8)
texture:SetPoint("TOPLEFT", MultiBarBottomRight, "TOPLEFT", -4, -4)
texture:SetPoint("BOTTOMRIGHT", MultiBarBottomRight, "BOTTOMRIGHT", 4, -8)
backgroundBarTexture(texture)
-- bar 4 --
local texture = MultiBarRight:CreateTexture("$parentABFbackground", "BACKGROUND", nil, -8)
texture:SetPoint("TOPLEFT", MultiBarRight, "TOPLEFT", -4, -4)
texture:SetPoint("BOTTOMRIGHT", MultiBarRight, "BOTTOMRIGHT", 4, -8)
backgroundBarTexture(texture)
-- bar 5 --
local texture = MultiBarLeft:CreateTexture("$parentABFbackground", "BACKGROUND", nil, -8)
texture:SetPoint("TOPLEFT", MultiBarLeft, "TOPLEFT", -4, -4)
texture:SetPoint("BOTTOMRIGHT", MultiBarLeft, "BOTTOMRIGHT", 4, -8)
backgroundBarTexture(texture)
-- bar 6 --
local texture = MultiBar5:CreateTexture("$parentABFbackground", "BACKGROUND", nil, -8)
texture:SetPoint("TOPLEFT", MultiBar5, "TOPLEFT", -4, -4)
texture:SetPoint("BOTTOMRIGHT", MultiBar5, "BOTTOMRIGHT", 4, -8)
backgroundBarTexture(texture)
-- bar 7 --
local texture = MultiBar6:CreateTexture("$parentABFbackground", "BACKGROUND", nil, -8)
texture:SetPoint("TOPLEFT", MultiBar6, "TOPLEFT", -4, -4)
texture:SetPoint("BOTTOMRIGHT", MultiBar6, "BOTTOMRIGHT", 4, -8)
backgroundBarTexture(texture)
-- bar 8 --
local texture = MultiBar7:CreateTexture("$parentABFbackground", "BACKGROUND", nil, -8)
texture:SetPoint("TOPLEFT", MultiBar7, "TOPLEFT", -4, -4)
texture:SetPoint("BOTTOMRIGHT", MultiBar7, "BOTTOMRIGHT", 4, -8)
backgroundBarTexture(texture)
-- Show background --
function abfShowBackground(self1, parent)
	local abfHorizontal = parent:DoesSettingValueEqual(Enum.EditModeActionBarSetting.Orientation, Enum.ActionBarOrientation.Horizontal)
	local abfVertical = parent:DoesSettingValueEqual(Enum.EditModeActionBarSetting.Orientation, Enum.ActionBarOrientation.Vertical)
	if abfHorizontal then
		self1:ClearAllPoints()
		self1:SetPoint("TOPLEFT", parent, "TOPLEFT", -4, -4)
		self1:SetPoint("BOTTOMRIGHT", parent, "BOTTOMRIGHT", 4, -8)
		self1:Show()
	elseif abfVertical then
		self1:ClearAllPoints()
		self1:SetPoint("TOPLEFT", parent, "TOPLEFT", -4, 4)
		self1:SetPoint("BOTTOMRIGHT", parent, "BOTTOMRIGHT", 4, -4)
		self1:Show()
	end
end
-- Creating the Slot Art 2 --
local function SlotArt2(self)
	self:SetAtlas("socket-prismatic-background", false, "LINEAR")
	self:Hide()
end
for i = 1, 12, 1 do
	local texture = _G["ActionButton".. i]:CreateTexture("$parentSlotArt2", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "ActionButton".. i, "TOPLEFT", 0, 0)
	texture:SetPoint("BOTTOMRIGHT", "ActionButton".. i, "BOTTOMRIGHT", 0, 0)
	SlotArt2(texture)
	local texture = _G["MultiBarBottomLeftButton".. i]:CreateTexture("$parentSlotArt2", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomLeftButton".. i, "TOPLEFT", 0, 0)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomLeftButton".. i, "BOTTOMRIGHT", 0, 0)
	SlotArt2(texture)
	local texture = _G["MultiBarBottomRightButton".. i]:CreateTexture("$parentSlotArt2", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomRightButton".. i, "TOPLEFT", 0, 0)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomRightButton".. i, "BOTTOMRIGHT", 0, 0)
	SlotArt2(texture)
	local texture = _G["MultiBarRightButton".. i]:CreateTexture("$parentSlotArt2", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarRightButton".. i, "TOPLEFT", 0, 0)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarRightButton".. i, "BOTTOMRIGHT", 0, 0)
	SlotArt2(texture)
	local texture = _G["MultiBarLeftButton".. i]:CreateTexture("$parentSlotArt2", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarLeftButton".. i, "TOPLEFT", 0, 0)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarLeftButton".. i, "BOTTOMRIGHT", 0, 0)
	SlotArt2(texture)
	local texture = _G["MultiBar5Button".. i]:CreateTexture("$parentSlotArt2", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar5Button".. i, "TOPLEFT", 0, 0)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar5Button".. i, "BOTTOMRIGHT", 0, 0)
	SlotArt2(texture)
	local texture = _G["MultiBar6Button".. i]:CreateTexture("$parentSlotArt2", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar6Button".. i, "TOPLEFT", 0, 0)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar6Button".. i, "BOTTOMRIGHT", 0, 0)
	SlotArt2(texture)
	local texture = _G["MultiBar7Button".. i]:CreateTexture("$parentSlotArt2", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar7Button".. i, "TOPLEFT", 0, 0)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar7Button".. i, "BOTTOMRIGHT", 0, 0)
	SlotArt2(texture)
end
-- Creating the Slot Art Nightfae --
-- front --
local function Nightfae(self)
	self:SetAtlas("CovenantSanctum-Text-Border-Nightfae", false, "LINEAR")
	self:Hide()
end
for i = 1, 12, 1 do
	local texture = _G["ActionButton".. i]:CreateTexture("$parentNightfae", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "ActionButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "ActionButton".. i, "BOTTOMRIGHT", -2, 0)
	Nightfae(texture)
	local texture = _G["MultiBarBottomLeftButton".. i]:CreateTexture("$parentNightfae", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	Nightfae(texture)
	local texture = _G["MultiBarBottomRightButton".. i]:CreateTexture("$parentNightfae", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomRightButton".. i, "BOTTOMRIGHT", -2, 0)
	Nightfae(texture)
	local texture = _G["MultiBarRightButton".. i]:CreateTexture("$parentNightfae", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarRightButton".. i, "BOTTOMRIGHT", -2, 0)
	Nightfae(texture)
	local texture = _G["MultiBarLeftButton".. i]:CreateTexture("$parentNightfae", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	Nightfae(texture)
	local texture = _G["MultiBar5Button".. i]:CreateTexture("$parentNightfae", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar5Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar5Button".. i, "BOTTOMRIGHT", -2, 0)
	Nightfae(texture)
	local texture = _G["MultiBar6Button".. i]:CreateTexture("$parentNightfae", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar6Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar6Button".. i, "BOTTOMRIGHT", -2, 0)
	Nightfae(texture)
	local texture = _G["MultiBar7Button".. i]:CreateTexture("$parentNightfae", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar7Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar7Button".. i, "BOTTOMRIGHT", -2, 0)
	Nightfae(texture)
end
-- back --
local function NightfaeBack1(self)
	self:SetAtlas("CovenantSanctum-Text-Border-Nightfae", false, "LINEAR")
	self:SetBlendMode("ADD")
	self:Hide()
end
for i = 1, 12, 1 do
	local texture = _G["ActionButton".. i]:CreateTexture("$parentNightfaeBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "ActionButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "ActionButton".. i, "BOTTOMRIGHT", -2, 0)
	NightfaeBack1(texture)
	local texture = _G["MultiBarBottomLeftButton".. i]:CreateTexture("$parentNightfaeBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarBottomLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	NightfaeBack1(texture)
	local texture = _G["MultiBarBottomRightButton".. i]:CreateTexture("$parentNightfaeBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarBottomRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomRightButton".. i, "BOTTOMRIGHT", -2, 0)
	NightfaeBack1(texture)
	local texture = _G["MultiBarRightButton".. i]:CreateTexture("$parentNightfaeBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarRightButton".. i, "BOTTOMRIGHT", -2, 0)
	NightfaeBack1(texture)
	local texture = _G["MultiBarLeftButton".. i]:CreateTexture("$parentNightfaeBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	NightfaeBack1(texture)
	local texture = _G["MultiBar5Button".. i]:CreateTexture("$parentNightfaeBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar5Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar5Button".. i, "BOTTOMRIGHT", -2, 0)
	NightfaeBack1(texture)
	local texture = _G["MultiBar6Button".. i]:CreateTexture("$parentNightfaeBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar6Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar6Button".. i, "BOTTOMRIGHT", -2, 0)
	NightfaeBack1(texture)
	local texture = _G["MultiBar7Button".. i]:CreateTexture("$parentNightfaeBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar7Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar7Button".. i, "BOTTOMRIGHT", -2, 0)
	NightfaeBack1(texture)
end
-- Creating the Slot Art Kyrian --
-- front --
local function Kyrian(self)
	self:SetAtlas("CovenantSanctum-Text-Border-Kyrian", false, "LINEAR")
	self:Hide()
end
for i = 1, 12, 1 do
	local texture = _G["ActionButton".. i]:CreateTexture("$parentKyrian", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "ActionButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "ActionButton".. i, "BOTTOMRIGHT", -2, 0)
	Kyrian(texture)
	local texture = _G["MultiBarBottomLeftButton".. i]:CreateTexture("$parentKyrian", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	Kyrian(texture)
	local texture = _G["MultiBarBottomRightButton".. i]:CreateTexture("$parentKyrian", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomRightButton".. i, "BOTTOMRIGHT", -2, 0)
	Kyrian(texture)
	local texture = _G["MultiBarRightButton".. i]:CreateTexture("$parentKyrian", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarRightButton".. i, "BOTTOMRIGHT", -2, 0)
	Kyrian(texture)
	local texture = _G["MultiBarLeftButton".. i]:CreateTexture("$parentKyrian", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	Kyrian(texture)
	local texture = _G["MultiBar5Button".. i]:CreateTexture("$parentKyrian", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar5Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar5Button".. i, "BOTTOMRIGHT", -2, 0)
	Kyrian(texture)
	local texture = _G["MultiBar6Button".. i]:CreateTexture("$parentKyrian", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar6Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar6Button".. i, "BOTTOMRIGHT", -2, 0)
	Kyrian(texture)
	local texture = _G["MultiBar7Button".. i]:CreateTexture("$parentKyrian", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar7Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar7Button".. i, "BOTTOMRIGHT", -2, 0)
	Kyrian(texture)
end
-- back --
local function KyrianBack1(self)
	self:SetAtlas("CovenantSanctum-Text-Border-Kyrian", false, "LINEAR")
	self:SetBlendMode("ADD")
	self:Hide()
end
for i = 1, 12, 1 do
	local texture = _G["ActionButton".. i]:CreateTexture("$parentKyrianBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "ActionButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "ActionButton".. i, "BOTTOMRIGHT", -2, 0)
	KyrianBack1(texture)
	local texture = _G["MultiBarBottomLeftButton".. i]:CreateTexture("$parentKyrianBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarBottomLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	KyrianBack1(texture)
	local texture = _G["MultiBarBottomRightButton".. i]:CreateTexture("$parentKyrianBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarBottomRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomRightButton".. i, "BOTTOMRIGHT", -2, 0)
	KyrianBack1(texture)
	local texture = _G["MultiBarRightButton".. i]:CreateTexture("$parentKyrianBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarRightButton".. i, "BOTTOMRIGHT", -2, 0)
	KyrianBack1(texture)
	local texture = _G["MultiBarLeftButton".. i]:CreateTexture("$parentKyrianBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	KyrianBack1(texture)
	local texture = _G["MultiBar5Button".. i]:CreateTexture("$parentKyrianBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar5Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar5Button".. i, "BOTTOMRIGHT", -2, 0)
	KyrianBack1(texture)
	local texture = _G["MultiBar6Button".. i]:CreateTexture("$parentKyrianBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar6Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar6Button".. i, "BOTTOMRIGHT", -2, 0)
	KyrianBack1(texture)
	local texture = _G["MultiBar7Button".. i]:CreateTexture("$parentKyrianBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar7Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar7Button".. i, "BOTTOMRIGHT", -2, 0)
	KyrianBack1(texture)
end
-- Creating the Slot Art Necrolord --
-- front --
local function Necrolord(self)
	self:SetAtlas("CovenantSanctum-Text-Border-Necrolord", false, "LINEAR")
	self:Hide()
end
for i = 1, 12, 1 do
	local texture = _G["ActionButton".. i]:CreateTexture("$parentNecrolord", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "ActionButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "ActionButton".. i, "BOTTOMRIGHT", -2, 0)
	Necrolord(texture)
	local texture = _G["MultiBarBottomLeftButton".. i]:CreateTexture("$parentNecrolord", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	Necrolord(texture)
	local texture = _G["MultiBarBottomRightButton".. i]:CreateTexture("$parentNecrolord", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomRightButton".. i, "BOTTOMRIGHT", -2, 0)
	Necrolord(texture)
	local texture = _G["MultiBarRightButton".. i]:CreateTexture("$parentNecrolord", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarRightButton".. i, "BOTTOMRIGHT", -2, 0)
	Necrolord(texture)
	local texture = _G["MultiBarLeftButton".. i]:CreateTexture("$parentNecrolord", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	Necrolord(texture)
	local texture = _G["MultiBar5Button".. i]:CreateTexture("$parentNecrolord", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar5Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar5Button".. i, "BOTTOMRIGHT", -2, 0)
	Necrolord(texture)
	local texture = _G["MultiBar6Button".. i]:CreateTexture("$parentNecrolord", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar6Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar6Button".. i, "BOTTOMRIGHT", -2, 0)
	Necrolord(texture)
	local texture = _G["MultiBar7Button".. i]:CreateTexture("$parentNecrolord", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar7Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar7Button".. i, "BOTTOMRIGHT", -2, 0)
	Necrolord(texture)
end
-- back --
local function NecrolordBack1(self)
	self:SetAtlas("CovenantSanctum-Text-Border-Necrolord", false, "LINEAR")
	self:SetBlendMode("ADD")
	self:Hide()
end
for i = 1, 12, 1 do
	local texture = _G["ActionButton".. i]:CreateTexture("$parentNecrolordBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "ActionButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "ActionButton".. i, "BOTTOMRIGHT", -2, 0)
	NecrolordBack1(texture)
	local texture = _G["MultiBarBottomLeftButton".. i]:CreateTexture("$parentNecrolordBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarBottomLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	NecrolordBack1(texture)
	local texture = _G["MultiBarBottomRightButton".. i]:CreateTexture("$parentNecrolordBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarBottomRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomRightButton".. i, "BOTTOMRIGHT", -2, 0)
	NecrolordBack1(texture)
	local texture = _G["MultiBarRightButton".. i]:CreateTexture("$parentNecrolordBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarRightButton".. i, "BOTTOMRIGHT", -2, 0)
	NecrolordBack1(texture)
	local texture = _G["MultiBarLeftButton".. i]:CreateTexture("$parentNecrolordBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	NecrolordBack1(texture)
	local texture = _G["MultiBar5Button".. i]:CreateTexture("$parentNecrolordBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar5Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar5Button".. i, "BOTTOMRIGHT", -2, 0)
	NecrolordBack1(texture)
	local texture = _G["MultiBar6Button".. i]:CreateTexture("$parentNecrolordBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar6Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar6Button".. i, "BOTTOMRIGHT", -2, 0)
	NecrolordBack1(texture)
	local texture = _G["MultiBar7Button".. i]:CreateTexture("$parentNecrolordBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar7Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar7Button".. i, "BOTTOMRIGHT", -2, 0)
	NecrolordBack1(texture)
end
-- Creating the Slot Art Venthyr --
-- front --
local function Venthyr(self)
	self:SetAtlas("CovenantSanctum-Text-Border-Venthyr", false, "LINEAR")
	self:Hide()
end
for i = 1, 12, 1 do
	local texture = _G["ActionButton".. i]:CreateTexture("$parentVenthyr", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "ActionButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "ActionButton".. i, "BOTTOMRIGHT", -2, 0)
	Venthyr(texture)
	local texture = _G["MultiBarBottomLeftButton".. i]:CreateTexture("$parentVenthyr", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	Venthyr(texture)
	local texture = _G["MultiBarBottomRightButton".. i]:CreateTexture("$parentVenthyr", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarBottomRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomRightButton".. i, "BOTTOMRIGHT", -2, 0)
	Venthyr(texture)
	local texture = _G["MultiBarRightButton".. i]:CreateTexture("$parentVenthyr", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarRightButton".. i, "BOTTOMRIGHT", -2, 0)
	Venthyr(texture)
	local texture = _G["MultiBarLeftButton".. i]:CreateTexture("$parentVenthyr", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBarLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	Venthyr(texture)
	local texture = _G["MultiBar5Button".. i]:CreateTexture("$parentVenthyr", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar5Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar5Button".. i, "BOTTOMRIGHT", -2, 0)
	Venthyr(texture)
	local texture = _G["MultiBar6Button".. i]:CreateTexture("$parentVenthyr", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar6Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar6Button".. i, "BOTTOMRIGHT", -2, 0)
	Venthyr(texture)
	local texture = _G["MultiBar7Button".. i]:CreateTexture("$parentVenthyr", "BACKGROUND", nil, 0)
	texture:SetPoint("TOPLEFT", "MultiBar7Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar7Button".. i, "BOTTOMRIGHT", -2, 0)
	Venthyr(texture)
end
-- back --
local function VenthyrBack1(self)
	self:SetAtlas("CovenantSanctum-Text-Border-Venthyr", false, "LINEAR")
	self:SetBlendMode("ADD")
	self:Hide()
end
for i = 1, 12, 1 do
	local texture = _G["ActionButton".. i]:CreateTexture("$parentVenthyrBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "ActionButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "ActionButton".. i, "BOTTOMRIGHT", -2, 0)
	VenthyrBack1(texture)
	local texture = _G["MultiBarBottomLeftButton".. i]:CreateTexture("$parentVenthyrBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarBottomLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	VenthyrBack1(texture)
	local texture = _G["MultiBarBottomRightButton".. i]:CreateTexture("$parentVenthyrBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarBottomRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarBottomRightButton".. i, "BOTTOMRIGHT", -2, 0)
	VenthyrBack1(texture)
	local texture = _G["MultiBarRightButton".. i]:CreateTexture("$parentVenthyrBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarRightButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarRightButton".. i, "BOTTOMRIGHT", -2, 0)
	VenthyrBack1(texture)
	local texture = _G["MultiBarLeftButton".. i]:CreateTexture("$parentVenthyrBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBarLeftButton".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBarLeftButton".. i, "BOTTOMRIGHT", -2, 0)
	VenthyrBack1(texture)
	local texture = _G["MultiBar5Button".. i]:CreateTexture("$parentVenthyrBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar5Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar5Button".. i, "BOTTOMRIGHT", -2, 0)
	VenthyrBack1(texture)
	local texture = _G["MultiBar6Button".. i]:CreateTexture("$parentVenthyrBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar6Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar6Button".. i, "BOTTOMRIGHT", -2, 0)
	VenthyrBack1(texture)
	local texture = _G["MultiBar7Button".. i]:CreateTexture("$parentVenthyrBack", "BACKGROUND", nil, 7)
	texture:SetPoint("TOPLEFT", "MultiBar7Button".. i, "TOPLEFT", 2, -2)
	texture:SetPoint("BOTTOMRIGHT", "MultiBar7Button".. i, "BOTTOMRIGHT", -2, 0)
	VenthyrBack1(texture)
end
