-- create edges textures animations --
local function CreateEdgesAnimations(bar)
	bar.actionButtons[1].EdgeLeftArtAnimation = bar.actionButtons[1]:CreateTexture(nil, "BACKGROUND", nil, 0)
	bar.actionButtons[1].EdgeLeftArtAnimation:SetDesaturated(true)
	bar.actionButtons[1].EdgeLeftArtAnimation:SetBlendMode("ADD")
	bar.actionButtons[1].EdgeLeftArtAnimation:Hide()

	bar.actionButtons[1].EdgeRightArtAnimation = bar.actionButtons[1]:CreateTexture(nil, "BACKGROUND", nil, 0)
	bar.actionButtons[1].EdgeRightArtAnimation:SetDesaturated(true)
	bar.actionButtons[1].EdgeRightArtAnimation:SetBlendMode("ADD")
	bar.actionButtons[1].EdgeRightArtAnimation:Hide()
	bar.actionButtons[1].Gryphon_WyvernAnimationLeft = bar.actionButtons[1]:CreateAnimationGroup(nil, "abfGryphon_WyvernAnimation")
	bar.actionButtons[1].Gryphon_WyvernAnimationRight = bar.actionButtons[1]:CreateAnimationGroup(nil, "abfGryphon_WyvernAnimation")
end
CreateEdgesAnimations(MainMenuBar)
CreateEdgesAnimations(MultiBarBottomLeft)
CreateEdgesAnimations(MultiBarBottomRight)
CreateEdgesAnimations(MultiBarRight)
CreateEdgesAnimations(MultiBarLeft)
CreateEdgesAnimations(MultiBar5)
CreateEdgesAnimations(MultiBar6)
CreateEdgesAnimations(MultiBar7)
-- create top textures animations --
local function CreateTopAnimations(bar)
	bar.actionButtons[1].TopArtAnimation = bar.actionButtons[1]:CreateTexture(nil, "BACKGROUND", nil, 1)
	bar.actionButtons[1].TopArtAnimation:SetPoint("BOTTOM", bar.actionButtons[1].TopArt, "CENTER", 0, -24)
	
	bar.actionButtons[1].TopArtAnimation:SetSize(208, 72)
	bar.actionButtons[1].TopArtAnimation:SetBlendMode("ADD")
	bar.actionButtons[1].TopArtAnimation:SetDesaturated(true)
	
	bar.actionButtons[1].TopArtAnimation:Show()
	bar.actionButtons[1].JailersTowerAnimation = bar.actionButtons[1]:CreateAnimationGroup(nil, "abfJailersTowerAnimation")
end
CreateTopAnimations(MainMenuBar)
CreateTopAnimations(MultiBarBottomLeft)
CreateTopAnimations(MultiBarBottomRight)
CreateTopAnimations(MultiBarRight)
CreateTopAnimations(MultiBarLeft)
CreateTopAnimations(MultiBar5)
CreateTopAnimations(MultiBar6)
CreateTopAnimations(MultiBar7)

local function CreateJailersEye(bar)
	bar.actionButtons[1].JailersEyeLeft = bar.actionButtons[1]:CreateTexture(nil, "OVERLAY", nil, 7)
	bar.actionButtons[1].JailersEyeLeft:SetPoint("CENTER", bar.actionButtons[1].TopArt, "CENTER", -10, 4)
	bar.actionButtons[1].JailersEyeLeft:SetAtlas("AnimaChannel-Bar-Necrolord-Gem", false, "LINEAR")
	bar.actionButtons[1].JailersEyeLeft:SetSize(5, 5)
	bar.actionButtons[1].JailersEyeLeft:SetDesaturated(true)
	bar.actionButtons[1].JailersEyeLeft:SetAlpha(1)
	bar.actionButtons[1].JailersEyeLeft:Hide()
	bar.actionButtons[1].JailersEyeRight = bar.actionButtons[1]:CreateTexture(nil, "OVERLAY", nil, 7)
	bar.actionButtons[1].JailersEyeRight:SetPoint("CENTER", bar.actionButtons[1].TopArt, "CENTER", 6, 4)
	bar.actionButtons[1].JailersEyeRight:SetAtlas("AnimaChannel-Bar-Necrolord-Gem", false, "LINEAR")
	bar.actionButtons[1].JailersEyeRight:SetSize(5, 5)
	bar.actionButtons[1].JailersEyeRight:SetDesaturated(true)
	bar.actionButtons[1].JailersEyeRight:SetAlpha(1)
	bar.actionButtons[1].JailersEyeRight:Hide()
end
CreateJailersEye(MainMenuBar)
CreateJailersEye(MultiBarBottomLeft)
CreateJailersEye(MultiBarBottomRight)
CreateJailersEye(MultiBarRight)
CreateJailersEye(MultiBarLeft)
CreateJailersEye(MultiBar5)
CreateJailersEye(MultiBar6)
CreateJailersEye(MultiBar7)

-- create Bottom textures animations --
local function CreateBottomAnimations(bar)
	bar.actionButtons[1].SoftCloudAnimation = bar.actionButtons[1]:CreateAnimationGroup(nil, "abfSoftCloudAnimation")
end
CreateBottomAnimations(MainMenuBar)
CreateBottomAnimations(MultiBarBottomLeft)
CreateBottomAnimations(MultiBarBottomRight)
CreateBottomAnimations(MultiBarRight)
CreateBottomAnimations(MultiBarLeft)
CreateBottomAnimations(MultiBar5)
CreateBottomAnimations(MultiBar6)
CreateBottomAnimations(MultiBar7)